use_frameworks!

target 'AgilFadeable_Example' do
  pod 'AgilFadeable', :path => '../'

  target 'AgilFadeable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
